// utils/icons.ts
import {
  GithubIcon,
  FileText,
  PenTool as Tool,
  Instagram,
  UserCircle,
  BadgeAlert,
  Badge,
  ListCollapse,
  Power,
  House,
  Component,
  Palette,
  LayoutGrid,
  SquareCheck,
  Star,
  IdCard,
  List,
  NotepadTextDashed,
  FormInput,
  FileUp,
  ChevronDown,
  Table,
  ToggleLeft,
  RectangleEllipsis,
  PanelTop,
  Workflow,
} from "lucide-react";


// central icon registry
export const Icons = {
  house: House,
  fileText: FileText,
  component: Component,
  palette: Palette,
  layoutGrid: LayoutGrid,
  power: Power,
  badge: Badge,
  userCircle: UserCircle,
  squareCheck: SquareCheck,
  badgeAlert: BadgeAlert,
  listCollapse: ListCollapse,
  github: GithubIcon,
  instagram: Instagram,
  tool: Tool,
  star: Star,
  IdCard: IdCard,
  list: List,
  notepadTextDashed: NotepadTextDashed,
  inputCursorText: FormInput,
  fileUpload: FileUp,
  chevronDown: ChevronDown,
  table: Table,
  toggle: ToggleLeft,
  pagination: RectangleEllipsis,
  panelTop: PanelTop,
  workflow: Workflow,
};

export type IconName = keyof typeof Icons;
